
openapi: 3.0.0
info:
  title: Bansu API
  version: 1.0.0
  description: API for managing and tracking Acedrg jobs, including job creation and progress tracking.

paths:
  /run_acedrg:
    post:
      summary: Creates an Acedrg job
      description: Creates an Acedrg job with a SMILES string and additional command-line arguments.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                smiles:
                  type: string
                  description: The SMILES string for the Acedrg job.
                commandline_args:
                  type: array
                  items:
                    type: string
                  description: An array of additional command-line arguments passed to Acedrg.
              required:
                - smiles
      responses:
        '201':
          description: Job spawned successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  job_id:
                    type: string
                    description: UUID of the job.
        '202':
          description: Job has been queued.
        '400':
          description: Input validation error.
        '503':
          description: Server at capacity.
        '500':
          description: Internal server error.

  /ws/{job_id}:
    get:
      summary: Track job progress
      description: Opens a WebSocket connection to track the job's progress.
      parameters:
        - name: job_id
          in: path
          required: true
          schema:
            type: string
            description: The UUID of the job.
      responses:
        '101':
          description: Switching protocols to WebSocket.
        '404':
          description: Job ID not found.

  /get_cif/{job_id}:
    get:
      summary: Get CIF file
      description: Streams the contents of the CIF file generated by Acedrg.
      parameters:
        - name: job_id
          in: path
          required: true
          schema:
            type: string
            description: The UUID of the job.
      responses:
        '200':
          description: CIF file retrieved successfully.
        '404':
          description: Job ID not found.
        '500':
          description: Output file could not be read.
        '400':
          description: Job ID is not valid or job is still pending.

components:
  schemas:
    JobProgress:
      type: object
      properties:
        status:
          type: string
          enum:
            - Pending
            - Finished
            - Failed
            - Queued
          description: The status of the job.
        queue_position:
          type: integer
          nullable: true
          description: Position in the queue, null if not queued.
        job_output:
          type: object
          nullable: true
          properties:
            stdout:
              type: string
              description: Standard output of the job.
            stderr:
              type: string
              description: Standard error of the job.
        error_message:
          type: string
          nullable: true
          description: Error message if the job failed.
        failure_reason:
          type: string
          enum:
            - TimedOut
            - JobProcessError
            - SetupError
          nullable: true
          description: Reason for job failure.
