//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "Jobs")]
pub struct Model {
    #[sea_orm(primary_key, unique)]
    pub id: i64,
    #[sea_orm(ignore, column_type = "custom(\"DATETIME\")", select_as = "text")]
    pub start_time: String,
    pub processing_time: Option<i64>,
    pub ip_address: i64,
    pub successful: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
